// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod lix {
        pub mod plugin {
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod api {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type CanonicalJson = _rt::String;
                #[derive(Clone)]
                pub struct File {
                    pub id: _rt::String,
                    pub path: _rt::String,
                    pub data: _rt::Vec<u8>,
                }
                impl ::core::fmt::Debug for File {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("File")
                            .field("id", &self.id)
                            .field("path", &self.path)
                            .field("data", &self.data)
                            .finish()
                    }
                }
                #[derive(Clone)]
                pub struct EntityChange {
                    pub entity_id: _rt::String,
                    pub schema_key: _rt::String,
                    pub snapshot_content: Option<CanonicalJson>,
                }
                impl ::core::fmt::Debug for EntityChange {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("EntityChange")
                            .field("entity-id", &self.entity_id)
                            .field("schema-key", &self.schema_key)
                            .field("snapshot-content", &self.snapshot_content)
                            .finish()
                    }
                }
                #[derive(Clone)]
                pub struct ActiveStateRow {
                    pub entity_id: _rt::String,
                    pub schema_key: Option<_rt::String>,
                    pub snapshot_content: Option<CanonicalJson>,
                    pub file_id: Option<_rt::String>,
                    pub plugin_key: Option<_rt::String>,
                    pub version_id: Option<_rt::String>,
                    pub change_id: Option<_rt::String>,
                    pub metadata: Option<CanonicalJson>,
                    pub created_at: Option<_rt::String>,
                    pub updated_at: Option<_rt::String>,
                }
                impl ::core::fmt::Debug for ActiveStateRow {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("ActiveStateRow")
                            .field("entity-id", &self.entity_id)
                            .field("schema-key", &self.schema_key)
                            .field("snapshot-content", &self.snapshot_content)
                            .field("file-id", &self.file_id)
                            .field("plugin-key", &self.plugin_key)
                            .field("version-id", &self.version_id)
                            .field("change-id", &self.change_id)
                            .field("metadata", &self.metadata)
                            .field("created-at", &self.created_at)
                            .field("updated-at", &self.updated_at)
                            .finish()
                    }
                }
                #[derive(Clone)]
                pub struct DetectStateContext {
                    pub active_state: Option<_rt::Vec<ActiveStateRow>>,
                }
                impl ::core::fmt::Debug for DetectStateContext {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("DetectStateContext")
                            .field("active-state", &self.active_state)
                            .finish()
                    }
                }
                #[derive(Clone)]
                pub enum PluginError {
                    InvalidInput(_rt::String),
                    Internal(_rt::String),
                }
                impl ::core::fmt::Debug for PluginError {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            PluginError::InvalidInput(e) => {
                                f.debug_tuple("PluginError::InvalidInput").field(e).finish()
                            }
                            PluginError::Internal(e) => {
                                f.debug_tuple("PluginError::Internal").field(e).finish()
                            }
                        }
                    }
                }
                impl ::core::fmt::Display for PluginError {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        write!(f, "{:?}", self)
                    }
                }
                impl std::error::Error for PluginError {}
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_detect_changes_cabi<T: Guest>(
                    arg0: *mut u8,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    let l10 = *arg0
                        .add(7 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l11 = *arg0
                        .add(8 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len12 = l11;
                    let bytes12 = _rt::Vec::from_raw_parts(l10.cast(), len12, len12);
                    let l13 = *arg0
                        .add(9 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l14 = *arg0
                        .add(10 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len15 = l14;
                    let bytes15 = _rt::Vec::from_raw_parts(l13.cast(), len15, len15);
                    let l16 = *arg0
                        .add(11 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l17 = *arg0
                        .add(12 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len18 = l17;
                    let l19 = i32::from(
                        *arg0.add(13 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
                    );
                    let result63 = T::detect_changes(
                        match l0 {
                            0 => None,
                            1 => {
                                let e = {
                                    let l1 = *arg0
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l2 = *arg0
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    let len3 = l2;
                                    let bytes3 = _rt::Vec::from_raw_parts(
                                        l1.cast(),
                                        len3,
                                        len3,
                                    );
                                    let l4 = *arg0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l5 = *arg0
                                        .add(4 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    let len6 = l5;
                                    let bytes6 = _rt::Vec::from_raw_parts(
                                        l4.cast(),
                                        len6,
                                        len6,
                                    );
                                    let l7 = *arg0
                                        .add(5 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l8 = *arg0
                                        .add(6 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    let len9 = l8;
                                    File {
                                        id: _rt::string_lift(bytes3),
                                        path: _rt::string_lift(bytes6),
                                        data: _rt::Vec::from_raw_parts(l7.cast(), len9, len9),
                                    }
                                };
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                        File {
                            id: _rt::string_lift(bytes12),
                            path: _rt::string_lift(bytes15),
                            data: _rt::Vec::from_raw_parts(l16.cast(), len18, len18),
                        },
                        match l19 {
                            0 => None,
                            1 => {
                                let e = {
                                    let l20 = i32::from(
                                        *arg0
                                            .add(14 * ::core::mem::size_of::<*const u8>())
                                            .cast::<u8>(),
                                    );
                                    DetectStateContext {
                                        active_state: match l20 {
                                            0 => None,
                                            1 => {
                                                let e = {
                                                    let l21 = *arg0
                                                        .add(15 * ::core::mem::size_of::<*const u8>())
                                                        .cast::<*mut u8>();
                                                    let l22 = *arg0
                                                        .add(16 * ::core::mem::size_of::<*const u8>())
                                                        .cast::<usize>();
                                                    let base62 = l21;
                                                    let len62 = l22;
                                                    let mut result62 = _rt::Vec::with_capacity(len62);
                                                    for i in 0..len62 {
                                                        let base = base62
                                                            .add(i * (29 * ::core::mem::size_of::<*const u8>()));
                                                        let e62 = {
                                                            let l23 = *base.add(0).cast::<*mut u8>();
                                                            let l24 = *base
                                                                .add(::core::mem::size_of::<*const u8>())
                                                                .cast::<usize>();
                                                            let len25 = l24;
                                                            let bytes25 = _rt::Vec::from_raw_parts(
                                                                l23.cast(),
                                                                len25,
                                                                len25,
                                                            );
                                                            let l26 = i32::from(
                                                                *base
                                                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                                                    .cast::<u8>(),
                                                            );
                                                            let l30 = i32::from(
                                                                *base
                                                                    .add(5 * ::core::mem::size_of::<*const u8>())
                                                                    .cast::<u8>(),
                                                            );
                                                            let l34 = i32::from(
                                                                *base
                                                                    .add(8 * ::core::mem::size_of::<*const u8>())
                                                                    .cast::<u8>(),
                                                            );
                                                            let l38 = i32::from(
                                                                *base
                                                                    .add(11 * ::core::mem::size_of::<*const u8>())
                                                                    .cast::<u8>(),
                                                            );
                                                            let l42 = i32::from(
                                                                *base
                                                                    .add(14 * ::core::mem::size_of::<*const u8>())
                                                                    .cast::<u8>(),
                                                            );
                                                            let l46 = i32::from(
                                                                *base
                                                                    .add(17 * ::core::mem::size_of::<*const u8>())
                                                                    .cast::<u8>(),
                                                            );
                                                            let l50 = i32::from(
                                                                *base
                                                                    .add(20 * ::core::mem::size_of::<*const u8>())
                                                                    .cast::<u8>(),
                                                            );
                                                            let l54 = i32::from(
                                                                *base
                                                                    .add(23 * ::core::mem::size_of::<*const u8>())
                                                                    .cast::<u8>(),
                                                            );
                                                            let l58 = i32::from(
                                                                *base
                                                                    .add(26 * ::core::mem::size_of::<*const u8>())
                                                                    .cast::<u8>(),
                                                            );
                                                            ActiveStateRow {
                                                                entity_id: _rt::string_lift(bytes25),
                                                                schema_key: match l26 {
                                                                    0 => None,
                                                                    1 => {
                                                                        let e = {
                                                                            let l27 = *base
                                                                                .add(3 * ::core::mem::size_of::<*const u8>())
                                                                                .cast::<*mut u8>();
                                                                            let l28 = *base
                                                                                .add(4 * ::core::mem::size_of::<*const u8>())
                                                                                .cast::<usize>();
                                                                            let len29 = l28;
                                                                            let bytes29 = _rt::Vec::from_raw_parts(
                                                                                l27.cast(),
                                                                                len29,
                                                                                len29,
                                                                            );
                                                                            _rt::string_lift(bytes29)
                                                                        };
                                                                        Some(e)
                                                                    }
                                                                    _ => _rt::invalid_enum_discriminant(),
                                                                },
                                                                snapshot_content: match l30 {
                                                                    0 => None,
                                                                    1 => {
                                                                        let e = {
                                                                            let l31 = *base
                                                                                .add(6 * ::core::mem::size_of::<*const u8>())
                                                                                .cast::<*mut u8>();
                                                                            let l32 = *base
                                                                                .add(7 * ::core::mem::size_of::<*const u8>())
                                                                                .cast::<usize>();
                                                                            let len33 = l32;
                                                                            let bytes33 = _rt::Vec::from_raw_parts(
                                                                                l31.cast(),
                                                                                len33,
                                                                                len33,
                                                                            );
                                                                            _rt::string_lift(bytes33)
                                                                        };
                                                                        Some(e)
                                                                    }
                                                                    _ => _rt::invalid_enum_discriminant(),
                                                                },
                                                                file_id: match l34 {
                                                                    0 => None,
                                                                    1 => {
                                                                        let e = {
                                                                            let l35 = *base
                                                                                .add(9 * ::core::mem::size_of::<*const u8>())
                                                                                .cast::<*mut u8>();
                                                                            let l36 = *base
                                                                                .add(10 * ::core::mem::size_of::<*const u8>())
                                                                                .cast::<usize>();
                                                                            let len37 = l36;
                                                                            let bytes37 = _rt::Vec::from_raw_parts(
                                                                                l35.cast(),
                                                                                len37,
                                                                                len37,
                                                                            );
                                                                            _rt::string_lift(bytes37)
                                                                        };
                                                                        Some(e)
                                                                    }
                                                                    _ => _rt::invalid_enum_discriminant(),
                                                                },
                                                                plugin_key: match l38 {
                                                                    0 => None,
                                                                    1 => {
                                                                        let e = {
                                                                            let l39 = *base
                                                                                .add(12 * ::core::mem::size_of::<*const u8>())
                                                                                .cast::<*mut u8>();
                                                                            let l40 = *base
                                                                                .add(13 * ::core::mem::size_of::<*const u8>())
                                                                                .cast::<usize>();
                                                                            let len41 = l40;
                                                                            let bytes41 = _rt::Vec::from_raw_parts(
                                                                                l39.cast(),
                                                                                len41,
                                                                                len41,
                                                                            );
                                                                            _rt::string_lift(bytes41)
                                                                        };
                                                                        Some(e)
                                                                    }
                                                                    _ => _rt::invalid_enum_discriminant(),
                                                                },
                                                                version_id: match l42 {
                                                                    0 => None,
                                                                    1 => {
                                                                        let e = {
                                                                            let l43 = *base
                                                                                .add(15 * ::core::mem::size_of::<*const u8>())
                                                                                .cast::<*mut u8>();
                                                                            let l44 = *base
                                                                                .add(16 * ::core::mem::size_of::<*const u8>())
                                                                                .cast::<usize>();
                                                                            let len45 = l44;
                                                                            let bytes45 = _rt::Vec::from_raw_parts(
                                                                                l43.cast(),
                                                                                len45,
                                                                                len45,
                                                                            );
                                                                            _rt::string_lift(bytes45)
                                                                        };
                                                                        Some(e)
                                                                    }
                                                                    _ => _rt::invalid_enum_discriminant(),
                                                                },
                                                                change_id: match l46 {
                                                                    0 => None,
                                                                    1 => {
                                                                        let e = {
                                                                            let l47 = *base
                                                                                .add(18 * ::core::mem::size_of::<*const u8>())
                                                                                .cast::<*mut u8>();
                                                                            let l48 = *base
                                                                                .add(19 * ::core::mem::size_of::<*const u8>())
                                                                                .cast::<usize>();
                                                                            let len49 = l48;
                                                                            let bytes49 = _rt::Vec::from_raw_parts(
                                                                                l47.cast(),
                                                                                len49,
                                                                                len49,
                                                                            );
                                                                            _rt::string_lift(bytes49)
                                                                        };
                                                                        Some(e)
                                                                    }
                                                                    _ => _rt::invalid_enum_discriminant(),
                                                                },
                                                                metadata: match l50 {
                                                                    0 => None,
                                                                    1 => {
                                                                        let e = {
                                                                            let l51 = *base
                                                                                .add(21 * ::core::mem::size_of::<*const u8>())
                                                                                .cast::<*mut u8>();
                                                                            let l52 = *base
                                                                                .add(22 * ::core::mem::size_of::<*const u8>())
                                                                                .cast::<usize>();
                                                                            let len53 = l52;
                                                                            let bytes53 = _rt::Vec::from_raw_parts(
                                                                                l51.cast(),
                                                                                len53,
                                                                                len53,
                                                                            );
                                                                            _rt::string_lift(bytes53)
                                                                        };
                                                                        Some(e)
                                                                    }
                                                                    _ => _rt::invalid_enum_discriminant(),
                                                                },
                                                                created_at: match l54 {
                                                                    0 => None,
                                                                    1 => {
                                                                        let e = {
                                                                            let l55 = *base
                                                                                .add(24 * ::core::mem::size_of::<*const u8>())
                                                                                .cast::<*mut u8>();
                                                                            let l56 = *base
                                                                                .add(25 * ::core::mem::size_of::<*const u8>())
                                                                                .cast::<usize>();
                                                                            let len57 = l56;
                                                                            let bytes57 = _rt::Vec::from_raw_parts(
                                                                                l55.cast(),
                                                                                len57,
                                                                                len57,
                                                                            );
                                                                            _rt::string_lift(bytes57)
                                                                        };
                                                                        Some(e)
                                                                    }
                                                                    _ => _rt::invalid_enum_discriminant(),
                                                                },
                                                                updated_at: match l58 {
                                                                    0 => None,
                                                                    1 => {
                                                                        let e = {
                                                                            let l59 = *base
                                                                                .add(27 * ::core::mem::size_of::<*const u8>())
                                                                                .cast::<*mut u8>();
                                                                            let l60 = *base
                                                                                .add(28 * ::core::mem::size_of::<*const u8>())
                                                                                .cast::<usize>();
                                                                            let len61 = l60;
                                                                            let bytes61 = _rt::Vec::from_raw_parts(
                                                                                l59.cast(),
                                                                                len61,
                                                                                len61,
                                                                            );
                                                                            _rt::string_lift(bytes61)
                                                                        };
                                                                        Some(e)
                                                                    }
                                                                    _ => _rt::invalid_enum_discriminant(),
                                                                },
                                                            }
                                                        };
                                                        result62.push(e62);
                                                    }
                                                    _rt::cabi_dealloc(
                                                        base62,
                                                        len62 * (29 * ::core::mem::size_of::<*const u8>()),
                                                        ::core::mem::size_of::<*const u8>(),
                                                    );
                                                    result62
                                                };
                                                Some(e)
                                            }
                                            _ => _rt::invalid_enum_discriminant(),
                                        },
                                    }
                                };
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                    );
                    _rt::cabi_dealloc(
                        arg0,
                        17 * ::core::mem::size_of::<*const u8>(),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let ptr64 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result63 {
                        Ok(e) => {
                            *ptr64.add(0).cast::<u8>() = (0i32) as u8;
                            let vec69 = e;
                            let len69 = vec69.len();
                            let layout69 = _rt::alloc::Layout::from_size_align_unchecked(
                                vec69.len() * (7 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                            let result69 = if layout69.size() != 0 {
                                let ptr = _rt::alloc::alloc(layout69).cast::<u8>();
                                if ptr.is_null() {
                                    _rt::alloc::handle_alloc_error(layout69);
                                }
                                ptr
                            } else {
                                ::core::ptr::null_mut()
                            };
                            for (i, e) in vec69.into_iter().enumerate() {
                                let base = result69
                                    .add(i * (7 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let EntityChange {
                                        entity_id: entity_id65,
                                        schema_key: schema_key65,
                                        snapshot_content: snapshot_content65,
                                    } = e;
                                    let vec66 = (entity_id65.into_bytes()).into_boxed_slice();
                                    let ptr66 = vec66.as_ptr().cast::<u8>();
                                    let len66 = vec66.len();
                                    ::core::mem::forget(vec66);
                                    *base
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len66;
                                    *base.add(0).cast::<*mut u8>() = ptr66.cast_mut();
                                    let vec67 = (schema_key65.into_bytes()).into_boxed_slice();
                                    let ptr67 = vec67.as_ptr().cast::<u8>();
                                    let len67 = vec67.len();
                                    ::core::mem::forget(vec67);
                                    *base
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len67;
                                    *base
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr67.cast_mut();
                                    match snapshot_content65 {
                                        Some(e) => {
                                            *base
                                                .add(4 * ::core::mem::size_of::<*const u8>())
                                                .cast::<u8>() = (1i32) as u8;
                                            let vec68 = (e.into_bytes()).into_boxed_slice();
                                            let ptr68 = vec68.as_ptr().cast::<u8>();
                                            let len68 = vec68.len();
                                            ::core::mem::forget(vec68);
                                            *base
                                                .add(6 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>() = len68;
                                            *base
                                                .add(5 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>() = ptr68.cast_mut();
                                        }
                                        None => {
                                            *base
                                                .add(4 * ::core::mem::size_of::<*const u8>())
                                                .cast::<u8>() = (0i32) as u8;
                                        }
                                    };
                                }
                            }
                            *ptr64
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len69;
                            *ptr64
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = result69;
                        }
                        Err(e) => {
                            *ptr64.add(0).cast::<u8>() = (1i32) as u8;
                            match e {
                                PluginError::InvalidInput(e) => {
                                    *ptr64
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (0i32) as u8;
                                    let vec70 = (e.into_bytes()).into_boxed_slice();
                                    let ptr70 = vec70.as_ptr().cast::<u8>();
                                    let len70 = vec70.len();
                                    ::core::mem::forget(vec70);
                                    *ptr64
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len70;
                                    *ptr64
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr70.cast_mut();
                                }
                                PluginError::Internal(e) => {
                                    *ptr64
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (1i32) as u8;
                                    let vec71 = (e.into_bytes()).into_boxed_slice();
                                    let ptr71 = vec71.as_ptr().cast::<u8>();
                                    let len71 = vec71.len();
                                    ::core::mem::forget(vec71);
                                    *ptr64
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len71;
                                    *ptr64
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr71.cast_mut();
                                }
                            }
                        }
                    };
                    ptr64
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_detect_changes<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base10 = l1;
                            let len10 = l2;
                            for i in 0..len10 {
                                let base = base10
                                    .add(i * (7 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let l3 = *base.add(0).cast::<*mut u8>();
                                    let l4 = *base
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l3, l4, 1);
                                    let l5 = *base
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l6 = *base
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l5, l6, 1);
                                    let l7 = i32::from(
                                        *base
                                            .add(4 * ::core::mem::size_of::<*const u8>())
                                            .cast::<u8>(),
                                    );
                                    match l7 {
                                        0 => {}
                                        _ => {
                                            let l8 = *base
                                                .add(5 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l9 = *base
                                                .add(6 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            _rt::cabi_dealloc(l8, l9, 1);
                                        }
                                    }
                                }
                            }
                            _rt::cabi_dealloc(
                                base10,
                                len10 * (7 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                        }
                        _ => {
                            let l11 = i32::from(
                                *arg0.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                            );
                            match l11 {
                                0 => {
                                    let l12 = *arg0
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l13 = *arg0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l12, l13, 1);
                                }
                                _ => {
                                    let l14 = *arg0
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l15 = *arg0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l14, l15, 1);
                                }
                            }
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_apply_changes_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                    arg4: *mut u8,
                    arg5: usize,
                    arg6: *mut u8,
                    arg7: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let len1 = arg3;
                    let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
                    let len2 = arg5;
                    let base13 = arg6;
                    let len13 = arg7;
                    let mut result13 = _rt::Vec::with_capacity(len13);
                    for i in 0..len13 {
                        let base = base13
                            .add(i * (7 * ::core::mem::size_of::<*const u8>()));
                        let e13 = {
                            let l3 = *base.add(0).cast::<*mut u8>();
                            let l4 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len5 = l4;
                            let bytes5 = _rt::Vec::from_raw_parts(l3.cast(), len5, len5);
                            let l6 = *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l7 = *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len8 = l7;
                            let bytes8 = _rt::Vec::from_raw_parts(l6.cast(), len8, len8);
                            let l9 = i32::from(
                                *base
                                    .add(4 * ::core::mem::size_of::<*const u8>())
                                    .cast::<u8>(),
                            );
                            EntityChange {
                                entity_id: _rt::string_lift(bytes5),
                                schema_key: _rt::string_lift(bytes8),
                                snapshot_content: match l9 {
                                    0 => None,
                                    1 => {
                                        let e = {
                                            let l10 = *base
                                                .add(5 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l11 = *base
                                                .add(6 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            let len12 = l11;
                                            let bytes12 = _rt::Vec::from_raw_parts(
                                                l10.cast(),
                                                len12,
                                                len12,
                                            );
                                            _rt::string_lift(bytes12)
                                        };
                                        Some(e)
                                    }
                                    _ => _rt::invalid_enum_discriminant(),
                                },
                            }
                        };
                        result13.push(e13);
                    }
                    _rt::cabi_dealloc(
                        base13,
                        len13 * (7 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result14 = T::apply_changes(
                        File {
                            id: _rt::string_lift(bytes0),
                            path: _rt::string_lift(bytes1),
                            data: _rt::Vec::from_raw_parts(arg4.cast(), len2, len2),
                        },
                        result13,
                    );
                    let ptr15 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result14 {
                        Ok(e) => {
                            *ptr15.add(0).cast::<u8>() = (0i32) as u8;
                            let vec16 = (e).into_boxed_slice();
                            let ptr16 = vec16.as_ptr().cast::<u8>();
                            let len16 = vec16.len();
                            ::core::mem::forget(vec16);
                            *ptr15
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len16;
                            *ptr15
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr16.cast_mut();
                        }
                        Err(e) => {
                            *ptr15.add(0).cast::<u8>() = (1i32) as u8;
                            match e {
                                PluginError::InvalidInput(e) => {
                                    *ptr15
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (0i32) as u8;
                                    let vec17 = (e.into_bytes()).into_boxed_slice();
                                    let ptr17 = vec17.as_ptr().cast::<u8>();
                                    let len17 = vec17.len();
                                    ::core::mem::forget(vec17);
                                    *ptr15
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len17;
                                    *ptr15
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr17.cast_mut();
                                }
                                PluginError::Internal(e) => {
                                    *ptr15
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (1i32) as u8;
                                    let vec18 = (e.into_bytes()).into_boxed_slice();
                                    let ptr18 = vec18.as_ptr().cast::<u8>();
                                    let len18 = vec18.len();
                                    ::core::mem::forget(vec18);
                                    *ptr15
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len18;
                                    *ptr15
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr18.cast_mut();
                                }
                            }
                        }
                    };
                    ptr15
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_apply_changes<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base3 = l1;
                            let len3 = l2;
                            _rt::cabi_dealloc(base3, len3 * 1, 1);
                        }
                        _ => {
                            let l4 = i32::from(
                                *arg0.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                            );
                            match l4 {
                                0 => {
                                    let l5 = *arg0
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l6 = *arg0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l5, l6, 1);
                                }
                                _ => {
                                    let l7 = *arg0
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l8 = *arg0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l7, l8, 1);
                                }
                            }
                        }
                    }
                }
                pub trait Guest {
                    fn detect_changes(
                        before: Option<File>,
                        after: File,
                        state_context: Option<DetectStateContext>,
                    ) -> Result<_rt::Vec<EntityChange>, PluginError>;
                    fn apply_changes(
                        file: File,
                        changes: _rt::Vec<EntityChange>,
                    ) -> Result<_rt::Vec<u8>, PluginError>;
                }
                #[doc(hidden)]
                macro_rules! __export_lix_plugin_api_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "lix:plugin/api@0.1.0#detect-changes")] unsafe extern "C" fn
                        export_detect_changes(arg0 : * mut u8,) -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_detect_changes_cabi::<$ty > (arg0) }
                        } #[unsafe (export_name =
                        "cabi_post_lix:plugin/api@0.1.0#detect-changes")] unsafe extern
                        "C" fn _post_return_detect_changes(arg0 : * mut u8,) { unsafe {
                        $($path_to_types)*:: __post_return_detect_changes::<$ty > (arg0)
                        } } #[unsafe (export_name =
                        "lix:plugin/api@0.1.0#apply-changes")] unsafe extern "C" fn
                        export_apply_changes(arg0 : * mut u8, arg1 : usize, arg2 : * mut
                        u8, arg3 : usize, arg4 : * mut u8, arg5 : usize, arg6 : * mut u8,
                        arg7 : usize,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_apply_changes_cabi::<$ty > (arg0, arg1, arg2, arg3, arg4,
                        arg5, arg6, arg7) } } #[unsafe (export_name =
                        "cabi_post_lix:plugin/api@0.1.0#apply-changes")] unsafe extern
                        "C" fn _post_return_apply_changes(arg0 : * mut u8,) { unsafe {
                        $($path_to_types)*:: __post_return_apply_changes::<$ty > (arg0) }
                        } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_lix_plugin_api_0_1_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 4 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 4
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub use alloc_crate::alloc;
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_plugin_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::lix::plugin::api::__export_lix_plugin_api_0_1_0_cabi!($ty with_types_in
        $($path_to_types_root)*:: exports::lix::plugin::api);
    };
}
#[doc(inline)]
pub(crate) use __export_plugin_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:lix:plugin@0.1.0:plugin:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 666] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x9d\x04\x01A\x02\x01\
A\x02\x01B\x1a\x01s\x04\0\x0ecanonical-json\x03\0\0\x01p}\x01r\x03\x02ids\x04pat\
hs\x04data\x02\x04\0\x04file\x03\0\x03\x01k\x01\x01r\x03\x09entity-ids\x0aschema\
-keys\x10snapshot-content\x05\x04\0\x0dentity-change\x03\0\x06\x01ks\x01r\x0a\x09\
entity-ids\x0aschema-key\x08\x10snapshot-content\x05\x07file-id\x08\x0aplugin-ke\
y\x08\x0aversion-id\x08\x09change-id\x08\x08metadata\x05\x0acreated-at\x08\x0aup\
dated-at\x08\x04\0\x10active-state-row\x03\0\x09\x01p\x0a\x01k\x0b\x01r\x01\x0ca\
ctive-state\x0c\x04\0\x14detect-state-context\x03\0\x0d\x01q\x02\x0dinvalid-inpu\
t\x01s\0\x08internal\x01s\0\x04\0\x0cplugin-error\x03\0\x0f\x01k\x04\x01k\x0e\x01\
p\x07\x01j\x01\x13\x01\x10\x01@\x03\x06before\x11\x05after\x04\x0dstate-context\x12\
\0\x14\x04\0\x0edetect-changes\x01\x15\x01j\x01\x02\x01\x10\x01@\x02\x04file\x04\
\x07changes\x13\0\x16\x04\0\x0dapply-changes\x01\x17\x04\0\x14lix:plugin/api@0.1\
.0\x05\0\x04\0\x17lix:plugin/plugin@0.1.0\x04\0\x0b\x0c\x01\0\x06plugin\x03\0\0\0\
G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.227.1\x10wit-bindge\
n-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
